server: 
  port: 8080
  servlet:
    context-path: /boot
   
#视图解析器    
spring: 
  mvc:
    view:
      prefix: /  
      suffix: .jsp   
 
#映射静态资源     
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload
      
#数据源
#spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?serverTimezone=GMT
    username: root
    password: root  
     

#mybatis配置   
mybatis: 
  type-aliases-package: com.cssl.pojo
  configuration: 
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
